#!/bin/lua

NC = "\27[0m"
PUR = "\27[0;4m"

sfpath = io.open("/proc/meminfo", "r")
sf = sfpath:read("*a")

TotStr = string.match(sf, "MemTotal:.-kB")
FreStr = string.match(sf, "MemFree:.-kB")
AvaStr = string.match(sf, "MemAvailable:.-kB")
BufStr = string.match(sf, "Buffers:.-kB")
CacStr = string.match(sf, "Cached:.-kB")
SlaStr = string.match(sf, "Slab:.-kB")

TotF = string.match(TotStr, "%d[%d.,]*") / 976.5625
FreF = string.match(FreStr, "%d[%d.,]*") / 976.5625
AvaF = string.match(AvaStr, "%d[%d.,]*") / 976.5625
BufF = string.match(BufStr, "%d[%d.,]*") / 976.5625
CacF = string.match(CacStr, "%d[%d.,]*") / 976.5625
SlaF = string.match(SlaStr, "%d[%d.,]*") / 976.5625

UseF = TotF - FreF - BufF - CacF - SlaF
rAvaF = TotF - UseF
pUseF = TotF - AvaF

TotI = string.format("%.0f", TotF)
FreI = string.format("%.0f", FreF)
AvaI = string.format("%.0f", AvaF)
BufI = string.format("%.0f", BufF)
CacI = string.format("%.0f", CacF)
SlaI = string.format("%.0f", SlaF)
UseI = string.format("%.0f", UseF)
rAvaI = string.format("%.0f", rAvaF)
rUseI = string.format("%.0f", pUseF)

print(string.format("╚╚╚ Live Mem Stats ╝╝╝ Powered by %s Lua %s\
Total:               %s MB\
Available:           %s MB\
Used (Active):       %s MB\
Used (+ Cache):      %s MB", PUR, NC, TotI, rAvaI, UseI, rUseI))
