#!/bin/lua

NC = "\27[0m"
PUR = "\27[0;4m"

sfpath = io.open("/proc/meminfo", "r")
sf = sfpath:read("*a")

TotF = string.match(sf, "MemTotal:%s-(%d+) kB") / 976.5625
FreF = string.match(sf, "MemFree:%s-(%d+) kB") / 976.5625
AvaF = string.match(sf, "MemAvailable:%s-(%d+) kB") / 976.5625
BufF = string.match(sf, "Buffers:%s-(%d+) kB") / 976.5625
CacF = string.match(sf, "Cached:%s-(%d+) kB") / 976.5625
SlaF = string.match(sf, "Slab:%s-(%d+) kB") / 976.5625

UseF = TotF - FreF - BufF - CacF - SlaF
rAvaF = TotF - UseF
pUseF = TotF - AvaF

TotI = string.format("%.0f", TotF)
FreI = string.format("%.0f", FreF)
AvaI = string.format("%.0f", AvaF)
BufI = string.format("%.0f", BufF)
CacI = string.format("%.0f", CacF)
SlaI = string.format("%.0f", SlaF)
UseI = string.format("%.0f", UseF)
rAvaI = string.format("%.0f", rAvaF)
rUseI = string.format("%.0f", pUseF)

print(string.format("╚╚╚ Live Mem Stats ╝╝╝ Powered by %s Lua %s\
Total:               %s MB\
Available:           %s MB\
Used (Active):       %s MB\
Used (+ Cache):      %s MB", PUR, NC, TotI, rAvaI, UseI, rUseI))
